### ISSUE TITLE
Fail to load.

### ISSUE THREAD

**Issue by ZeroCool22** [isekaidev/stable.art#39]
![Screenshot_6](https://user-images.githubusercontent.com/13344308/216298448-d60319ad-eb30-441c-9da2-95c5437e9fc3.jpg)

**PS Version:** 24.0.1

**Comment by isekaidev** [comment]
Duplicate #12
I will add the offline mod after outpainting

**Comment by ZeroCool22** [comment]
> Duplicate #12 I will add the offline mod after outpainting

![giphy](https://user-images.githubusercontent.com/13344308/216502298-526adaa5-574e-4137-aba2-048832bda3ee.gif)

**Comment by Oleksandr5555** [comment]
Dear developer, when do you plan to update the plugin? It won’t start without the Internet, I have Photoshop closed by a firewall because if I open it, a window will appear warning me about deactivating Photoshop, it’s unlicensed.
After  editing the index can't see list of models and choise of quantity generated pictures,some options are missed upscalle,downscalle) . I really want it to work fully locally without an Internet connection.When the Internet is turned off, it appears Fail to load.
Thank you with best regards.
