### ISSUE TITLE
When prompt or negative prompt is very long it bugs the input box.

### ISSUE THREAD

**Issue by Drakmour** [isekaidev/stable.art#44]
When prompt or negative prompt is very long it bugs the input box. You can't see the prompt, you can't change anything in it, when you push it, it just make outline blue then nothing. Adress of A1111 is entered, I just erased it for secure purposes.
![5n8C7HXoE1](https://user-images.githubusercontent.com/119953290/216999339-31a5f727-15a1-41dc-8244-9238fd37febd.png)

**Comment by Drakmour** [comment]
> I will add a limit to a maximum height tomorrow,

A limit? Will it limit the maximum length of prompt? Or will fix the bugging of text?

> for a workaround right now, try to increase the width of the panel/plugin before typing (so the height of the textarea will be decreased).

Thanks! It worked! It still blinks when I scroll up and down, but at least it allows to further work. Thanks!

**Comment by isekaidev** [comment]
> Or will fix the bugging of text?

This. This limit will be applied only to the appearance. You still will be able to type prompts of any length.

Btw, I also noticed that this bug appears only when the start or the end of the field is outside of view. So, another workaround right now will be to scroll below so that the whole field can be viewed.

**Comment by Drakmour** [comment]
I have a wide monitor 2560x1080 so i just stretched this tab wide as possible and it works fine, I even can change the prompt, so I just collapse tab when I need to get to my image and do all tab manipulations in max width. Works for now. Tried to shrink the tab after inserting the prompt, it works to but when I try to change something in prompt it bugs again. And the only way (I think that the only way, haven't find the way to restart plugin without restarting Photoshop) to fix it is restart Photoshop. But, as I said, this  workaround works for now. Look forward for fixing. Gread plugin. Easy install, easy to work with.
Whe only question, why a generated image has mask by default?

**Comment by isekaidev** [comment]
Fixed, however, it still "blinks" and I cannot fix it because this is the bug of Photoshop itself. Hope, Adobe will fix it.

> Whe only question, why a generated image has mask by default?

The plugin adds a mask only for img2img/inpaint modes, and I think users need it 90% of the time, so the generated images can be smoothly integrated into an original image. Does this not apply to your use cases?

**Comment by Drakmour** [comment]
> Does this not apply to your use cases?

I just don't use masks in photoshop in general. I don't quite understand how they work and why I need them. :-D But i'm not that good photoshop user, I can do mediocre things, but I don't use 100% of all the instruments.

But overall thanks for the fix!
